### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by JupyterJones** [aryajur/lua-plot#3]
i do not even see a hint how to install. After three hours of trying I gave up.

**Comment by aryajur** [comment]
What did you try in 3 hours? It is just a lua file module. There is no specific installation. If you have used lua before then you just place the file where your Lua installation looks for files when you do require. These paths are defined in package.path.
      You do need the dependencies installed which are mentioned in the documentation. Dependency installation should be looked at each dependency project page.

**Comment by aryajur** [comment]
I will close this issue since I have had no further response. If you are still not able to install then please reopen.
